name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  macos-build:
    name: Build for macOS 🍏
    runs-on: macos-15
    defaults:
      run:
        shell: zsh --no-rcs --errexit --pipefail {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Enable Xcode 16.1
        run: sudo xcode-select --switch /Applications/Xcode_16.1.0.app/Contents/Developer

      - uses: actions/cache/restore@v4
        id: ccache-cache
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-RelWithDebInfo
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo

      - name: Build Unit Tests 🧪
        run: cmake --build build_macos --target obs-backuper-core-tests --config RelWithDebInfo

      - name: Run Unit Tests 🧪
        run: ctest --test-dir build_macos --build-config RelWithDebInfo --output-on-failure

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo
          package: true

      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: obs-bakeup-macos-universal-${{ github.sha }}
          path: ${{ github.workspace }}/release/obs-bakeup-*-macos-universal.*

      - uses: actions/cache/save@v4
        if: github.event_name != 'pull_request' && steps.ccache-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-RelWithDebInfo

  windows-build:
    name: Build for Windows 🪟
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: x64
          config: RelWithDebInfo

      - name: Run Unit Tests 🧪
        run: ctest --test-dir build_x64 --build-config RelWithDebInfo --output-on-failure

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: x64
          config: RelWithDebInfo
          package: true

      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: obs-bakeup-windows-x64-${{ github.sha }}
          path: ${{ github.workspace }}/release/obs-bakeup-*-windows-x64*.*
